# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  landotbien_backend:
    build:
      context: "/Volumes/Hoaq's Gke dit bu/FU/Kì 7/SWD391/BackEnd_LANDOTBIEN"
      dockerfile: "LanDotBien_BackEnd/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/LanDotBien_BackEnd.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "landotbienbackend:dev"
    ports: []
    volumes:
    - "/Users/hoangdinh/.nuget/packages:/root/.nuget/packages"
    - "/Volumes/Hoaq's Gke dit bu/FU/Kì 7/SWD391/BackEnd_LANDOTBIEN/LanDotBien_BackEnd:/app:rw"
    - "/Volumes/Hoaq's Gke dit bu/FU/Kì 7/SWD391/BackEnd_LANDOTBIEN:/src:rw"
    working_dir: "/app"
