version: '3.4'

services:
  landotbien_backend:
    image: ${DOCKER_REGISTRY-}landotbienbackend
    build:
      context: .
      dockerfile: LanDotBien_BackEnd/Dockerfile

  landotbien_backend-1:
    image: landotbien_backend-1
    build:
      context: .
      dockerfile: LanDotBien_BackEnd/Dockerfile

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

volumes:
  mysql_data: